training_management/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('web-portal/', include('web.urls')),
]

web/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required


from web.views.index import Index
from web.views.authentication.login import Login
from web.views.authentication.logout import Logout

from web.views.users.list import UserView
from web.views.users.add import UserAdd
from web.views.users.delete import delete_user
from web.views.users.management import UserManagement
from web.views.users.evaluate import UserEvaluate

from web.views.courses.list import CourseView
from web.views.courses.add import CourseAdd
from web.views.courses.delete import delete_course
from web.views.courses.management import CourseManagement

from web.views.documents.upload import DocumentUploadView
from web.views.documents.list import DocumentView
from web.views.documents.download import download
from web.views.documents.delete import delete_document


app_name = 'web'


urlpatterns = [
    url(r'^$', login_required(Index.as_view()), name="web-index"),
    url(r'^login/$', Login.as_view(), name='login'),
    url(r'^logout/$', Logout.as_view(), name='logout'),
    url(r'^user/$', login_required(UserView.as_view()), name="user_list"),
    url(r'^user/add/$', login_required(UserAdd.as_view()), name="user_add"),
    url(r'^user/delete/(?P<user_id>[0-9A-Za-z]+)$', delete_user, name="user_delete"),
    url(r'^user/management/(?P<user_id>[0-9A-Za-z]+)$', login_required(UserManagement.as_view()), name="user_management"),
    url(r'^course/$', login_required(CourseView.as_view()), name="course_list"),
    url(r'^course/add/$', login_required(CourseAdd.as_view()), name="course_add"),
    url(r'^course/delete/(?P<course_id>[0-9A-Za-z]+)$', delete_course, name="course_delete"),
    url(r'^course/management/(?P<course_id>[0-9A-Za-z]+)$', login_required(CourseManagement.as_view()), name="course_management"),
    url(r'^course/evaluation/(?P<course_id>[0-9A-Za-z]+)/(?P<user_id>[0-9A-Za-z]+)$', login_required(UserEvaluate.as_view()), name="evaluate_user"),
    url(r'^document/$', login_required(DocumentView.as_view()), name="document_list"),
    url(r'^document/upload/$', login_required(DocumentUploadView.as_view()), name="document_upload"),
    url(r'^document/download/(?P<doc_id>[0-9A-Za-z]+)$', download, name="document_download"),
    url(r'^document/delete/(?P<doc_id>[0-9A-Za-z]+)$', delete_document, name="document_delete"),
]

web/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


TEACHER = 1
STUDENT = 0
ROLE_CHOICES = (
    (STUDENT, 'student'),
    (TEACHER, 'teacher'),
)


class User(AbstractUser):
    employee_id = models.IntegerField(unique=True, null=True)
    full_name = models.CharField(max_length=255, null=True)
    role = models.SmallIntegerField(choices=ROLE_CHOICES, null=True)
    department = models.CharField(max_length=255, null=True)

    def get_role(self):
        return ROLE_CHOICES[int(self.role)][1]

    class Meta:
        permissions = (
            ('manage_users', 'Can manage users'),
        )


class Courses(models.Model):
    name = models.CharField(max_length=255, unique=True)
    start_date = models.DateField(null=True)
    end_date = models.DateField(null=True)
    users = models.ManyToManyField(User)

    class Meta:
        permissions = (
            ('manage_courses', 'Can manage courses'),
            ('search_courses', 'Can search courses'),
        )


class Documents(models.Model):
    title = models.CharField(max_length=255, unique=True)
    author = models.CharField(max_length=255, null=True)
    file_name = models.CharField(max_length=255)
    uploaded_by = models.CharField(max_length=255, null=True)
    course = models.ForeignKey(Courses, on_delete=models.CASCADE, to_field='name')

    class Meta:
        permissions = (
            ('download_documents', 'Can download documents'),
            ('search_documents', 'Can search documents'),
        )


class Evaluation(models.Model):
    class Meta:
        unique_together = (('student_id'), ('course_name'))
        permissions = (
            ('view_evaluation', 'Can view evaluation'),
        )

    student_id = models.IntegerField(null=True)
    course_name = models.CharField(max_length=255, null=True)
    assessor_id = models.IntegerField(null=True)
    assessor_name = models.CharField(max_length=255, null=True)
    evaluation = models.TextField(null=True)

web/views/index.py
from django.views.generic.base import TemplateView
from django.shortcuts import render


class Index(TemplateView):

    template_name = 'web/index.html'

    def get(self, request, **kwargs):
        return render(request, self.template_name, context={'user': request.user.username })

templates/base.html
<!doctype html>
<html class="no-js" lang="">
{% load bootstrap3 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
<head>
    <meta charset="utf-8">
    <title>Training Management</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width">
    {% block body_stylesheet %}
    {% endblock %}
</head>
<body style="background-color: #DCDCDC;">
{% block body_content %}
<style>
.btn {
    border: 1px solid black;
    background-color: white;
    color: black;
    cursor: pointer;
}

/* Green */
.success {
    border-color: #4CAF50;
    color: green;
}

.success:hover {
    background-color: #4CAF50;
    color: white;
}

/* Blue */
.primary {
    border-color: #2196F3;
    color: dodgerblue
}

.primary:hover {
    background: #2196F3;
    color: white;
}


/* Red */
.danger {
    border-color: #f44336;
    color: red
}

.danger:hover {
    background: #f44336;
    color: white;
}

/* Gray */
.default {
    border-color: #e7e7e7;
    color: black;
}

.default:hover {
    background: #e7e7e7;
}
</style>
<div class="app layout-fixed-header">

    <!--sidebar-panel-->
    {% include 'navigation.html' %}

    <!-- content panel -->
    <div class="main-panel">
        <!-- top header -->
        <div class="main-content" style="margin-left: 50px">
            {% block content %}
            {% endblock %}
        </div>
    </div>
</div>
{% endblock %}
{% block body_js %}
{% endblock %}
</body>
</html>

templates/message.html
{% load bootstrap3 %}

<div class="row">
    <div class="col-md-7">
        {% bootstrap_javascript jquery=1 %}
        {% bootstrap_messages %}
    </div>
</div>

templates/navigation.html
{% block sidebar_panel %}
    <div class="sidebar-panel offscreen-left">
        <nav class="navbar navbar-inverse">
            <div class="container-fluid">
                <div class="navbar-header">
                    <a class="navbar-brand" style="color: #F07E01;font-size: 24px;">CO-WELL Training</a>
                </div>
                <ul class="nav navbar-nav">
                    {% if request.user.is_authenticated %}
                        <li {% if request.path == '/web-portal/' %}class="active"{% endif %}><a href="{% url 'web:web-index' %}">Home </a></li>
                        {% if perms.web.manage_users %}
                            <li {% if 'user' in request.path %}class="active"{% endif %}><a href="{% url 'web:user_list' %}">Users</a></li>
                        {% endif %}
                        {% if perms.web.search_courses %}
                            <li {% if 'course' in request.path %}class="active"{% endif %}><a href="{% url 'web:course_list' %}">Courses</a></li>
                        {% endif %}
                        {% if perms.web.search_documents %}
                            <li {% if 'document' in request.path %}class="active"{% endif %}><a href="{% url 'web:document_list' %}">Document</a></li>
                        {% endif %}
                        <li><a href="{% url 'web:logout' %}">Logout</a></li>
                    {% endif %}
                </ul>
            </div>
        </nav>
    </div>
{% endblock %}

templates/permission_denied.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% block content %}
    {% include "message.html" %}
{% endblock %}

web/templates/web/courses/add.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% block content %}
    <div class="row">
        <div class="col-md-7">
            <h3 class="col-md-4">Add New Course</h3>
        </div>
    </div>

    {% include "message.html" %}

    <form role="form" class="form-horizontal" method="post">
        {% csrf_token %}
        <div class="row">
            <div class="col-md-7">
                {% bootstrap_form form %}
            </div>
        </div>
        <div style="margin-left: -15px; margin-top: 20px">
            <button type="submit" class="btn success">Add</button>
            <a href="{% url 'web:course_list' %}" type="button" class="btn default">Cancel</a>
        </div>
    </form>
{% endblock %}

web/templates/web/courses/list.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% load static %}
{% block content %}
    <div class="row">
        <div class="col-md-7">
            <h3 class="col-md-4">Courses</h3>
            {% if 'user.add_courses' in perms %}
            <a href="{% url 'web:course_add' %}" type="button" class="btn success pull-right" style="margin-top: 15px">Add</a>
            {% endif %}
        </div>
    </div>

    {% include "message.html" %}

    <form role="form" class="form-horizontal" method="post">
        {% csrf_token %}
        <div class="row">
            <div class="col-md-7">
                {% bootstrap_form form %}
            </div>
        </div>
        <button class="btn success" type="submit" style="margin-left: -15px">Search</button>
    </form>
    <div class="col-md-7">
    <table class="table table-striped table-bordered table-condensed responsive mb0" style="background: #93a1aa; color: black; margin-top: 20px">
        <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Start Date</th>
                <th>End Date</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            {% for c in courses %}
            <tr>
                <td>{{ c.0 }}</td>
                <td>{{ c.1 }}</td>
                <td>{{ c.2|default_if_none:'' }}</td>
                <td>{{ c.3|default_if_none:'' }}</td>
                <td>
                    {% if perms.web.manage_courses %}
                    <a href="{% url 'web:course_management' c.0 %}" class="btn btn-xs primary">Management</a>
                    {% endif %}
                    {% if perms.web.delete_courses %}
                    <button class="btn btn-xs danger" onclick="remove(this)"
                        data-id="{{ c.0 }}" data-url="{% url 'web:course_delete' c.0 %}">Remove</button>
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
        </tbody>
        </table>
    </div>
{% endblock %}

{% block body_js %}
<script src="{% static 'vendor/jquery/dist/jquery.min.js' %}"></script>
<script src="{% static 'vendor/sweetalert/sweetalert.2.0.min.js' %}"></script>
<script>
function remove(e) {
    var id = e.getAttribute('data-id');
    swal({
        icon: "warning",
        title: 'You are removing course "' + id +'"!',
        buttons: true,
        dangerMode: true,
        closeOnClickOutside: false
    }).then(function(ok) {
        if(ok) {
            var url = e.getAttribute('data-url');
            $.ajax({
                url: url,
                type: "GET",
                success: function (response) {
                    location.reload()
                },
            })
        }
    })
}


</script>
{% endblock %}

web/templates/web/courses/management.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% load static %}
{% block content %}
    <div class="row">
        <div class="col-md-7">
            <h3 class="col-md-4">Course Management</h3>
        </div>
    </div>

    {% include "message.html" %}

    <form role="form" class="form-horizontal" method="post">
        {% csrf_token %}
        <div class="row">
            <div class="col-md-7">
                {% bootstrap_form form %}
            </div>
        </div>
        <div class="row">
            <label>Users</label>
        </div>
        <div class="row">
            <div class="col-md-7">
                <table class="table table-striped table-bordered table-condensed responsive mb0" style="background: #93a1aa; color: black;">
                <thead>
                    <tr>
                        <th class="col-xs-1"><input type="checkbox" name="select-all" id="select-all" {% if not perms.web.change_courses %}disabled{% endif %}/></th>
                        <th class="col-md-2">Employee ID</th>
                        <th class="col-md-3">Name</th>
                        <th class="col-md-1">Department</th>
                        <th class="col-md-1">Role</th>
                        <th class="col-md-1">Action</th>
                    </tr>
                </thead>
                <tbody>
                    {% for s in users %}
                    {% if s.0|slugify in joined_user_id %}
                        {% if s.13 is not None %}
                            <tr class="checkboxlist">
                                <td><input type="checkbox" name="users" value="{{ s.0 }}" checked {% if not perms.web.change_courses %}disabled{% endif %} title=""/></td>
                                <td>{{ s.11 }}</td>
                                <td>{{ s.12 }}</td>
                                <td>{{ s.14|default_if_none:'' }}</td>
                                <td>{{ s.13|yesno:'Teacher,Student' }}</td>
                                <td>
                                    {% if perms.web.view_evaluation %}
                                    {% if s.13 == 0 %}
                                        <a href="{% url 'web:evaluate_user' course_id s.11 %}" class="btn primary btn-xs">Evaluate</a>
                                    {% endif %}
                                    {% endif %}
                                </td>
                            </tr>
                        {% endif %}
                    {% endif %}
                    {% endfor %}

                    {% for s in users %}
                    {% if s.0|slugify not in joined_user_id %}
                        {% if s.13 is not None %}
                            <tr class="checkboxlist">
                                <td><input type="checkbox" name="users" value="{{ s.0 }}" {% if not perms.web.change_courses %}disabled{% endif %} title=""/></td>
                                <td>{{ s.11 }}</td>
                                <td>{{ s.12 }}</td>
                                <td>{{ s.14|default_if_none:'' }}</td>
                                <td>{{ s.13|yesno:'Teacher,Student' }}</td>
                                <td>
                                </td>
                            </tr>
                        {% endif %}
                    {% endif %}
                    {% endfor %}
                </tbody>
                </table>
            </div>
        </div>
        <div style="margin-left: -15px; margin-top: 20px" class="row">
            {% if perms.web.change_courses %}
            <button type="submit" class="btn success">Save</button>
            <a href="{% url 'web:course_list' %}" type="button" class="btn default">Cancel</a>
            {% else %}
            <a href="{% url 'web:course_list' %}" type="button" class="btn default">Back</a>
            {% endif %}
        </div>
    </form>
{% endblock %}

{% block body_js %}
<script src="{% static 'vendor/jquery/dist/jquery.min.js' %}"></script>
<script>
    $('#select-all').on('change', function() {
        $('.checkboxlist input[type="checkbox"]').prop('checked', this.checked);
    });

    $('.checkboxlist input[type="checkbox"]').on('change', function () {
        var allChecked = $('.checkboxlist input:checked').length === $('.checkboxlist input').length;
        $('#select-all').prop('checked', allChecked);
    });


</script>
{% endblock %}

web/templates/web/documents/list.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% load static %}
{% block content %}
    <div class="row">
        <div class="col-md-7">
            <h3 class="col-md-4">Documents</h3>
            {% if perms.web.add_documents %}
            <a href="{% url 'web:document_upload' %}" type="button" class="btn success pull-right" style="margin-top: 15px">Upload</a>
            {% endif %}
        </div>
    </div>

    {% include "message.html" %}

    <form role="form" class="form-horizontal" method="post">
        {% csrf_token %}
        <div class="row">
            <div class="col-md-7">
                {% bootstrap_form form %}
                <div style="margin-left: -15px;">
                    <label>Course</label>
                    <select class="form-control" style="width: auto;" name="course">
                        <option value="">All</option>
                        {% for c in courses %}
                            <option value="{{ c.1 }}" {% if c.1|slugify == course|slugify %}selected{% endif %}>{{ c.1 }}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>
        </div>
        <div style="margin-left: -15px; margin-top: 20px">
            <button type="submit" class="btn success">Search</button>
        </div>
    </form>
    <div class="col-md-7">
    <table class="table table-striped table-bordered table-condensed responsive mb0" style="background: #93a1aa; color: black; margin-top: 20px">
        <thead>
            <tr>
                <th>ID</th>
                <th>Title</th>
                <th>Author</th>
                <th>Uploaded By</th>
                <th>Course</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            {% for d in documents %}
            <tr>
                <td>{{ d.0 }}</td>
                <td>{{ d.1 }}</td>
                <td>{{ d.2|default_if_none:'' }}</td>
                <td>{{ d.4|default_if_none:'' }}</td>
                <td>{{ d.5 }}</td>
                <td>
                    {% if perms.web.download_documents %}
                    <a href="{% url 'web:document_download' d.0 %}" class="btn btn-xs primary">Download</a>
                    {% endif %}
                    {% if perms.web.delete_documents %}
                    <button class="btn btn-xs danger" onclick="remove(this)"
                        data-id="{{ d.0 }}" data-url="{% url 'web:document_delete' d.0 %}">Remove</button>
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
        </tbody>
        </table>
    </div>
{% endblock %}

{% block body_js %}
<script src="{% static 'vendor/jquery/dist/jquery.min.js' %}"></script>
<script src="{% static 'vendor/sweetalert/sweetalert.2.0.min.js' %}"></script>
<script>
function remove(e) {
    var id = e.getAttribute('data-id');
    swal({
        icon: "warning",
        title: 'You are removing course "' + id +'"!',
        buttons: true,
        dangerMode: true,
        closeOnClickOutside: false
    }).then(function(ok) {
        if(ok) {
            var url = e.getAttribute('data-url');
            $.ajax({
                url: url,
                type: "GET",
                success: function (response) {
                    location.reload()
                },
            })
        }
    })
}


</script>
{% endblock %}

web/templates/web/documents/upload.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% block content %}
    <div class="row">
        <div class="col-md-7">
            <h3 class="col-md-4">Upload Document</h3>
        </div>
    </div>

    {% include "message.html" %}

    <form role="form" class="form-horizontal" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="row">
            <div class="col-md-7">
                {% bootstrap_form form %}
                <div style="margin-left: -15px;">
                    <label>Course</label>
                    <select class="form-control" style="width: auto;" name="course">
                        {% for c in courses %}
                            <option value="{{ c.0 }}" {% if c.0|slugify == course|slugify %}selected{% endif %}>{{ c.1 }}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>
        </div>
        <div style="margin-left: -15px; margin-top: 20px">
            {% if can_upload %}
            <button type="submit" class="btn success">Upload</button>
            {% endif %}
            <a href="{% url 'web:document_list' %}" type="button" class="btn default">Cancel</a>
        </div>
    </form>
{% endblock %}

web/templates/web/index.html
{% extends "base.html" %}
{% block content %}
<h1>
    Welcome {{ user }}
</h1>
    {% include "message.html" %}
{% endblock %}

web/templates/web/users/add.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% block content %}
    <div class="row">
        <div class="col-md-7">
            <h3 class="col-md-4">Add New User</h3>
        </div>
    </div>

    {% include "message.html" %}

    <form role="form" class="form-horizontal" method="post">
        {% csrf_token %}
        <div class="row">
            <div class="col-md-7">
                {% bootstrap_form form %}
            </div>
        </div>
        <div style="margin-left: -15px; margin-top: 20px">
            <button type="submit" class="btn success">Add</button>
            <a href="{% url 'web:user_list' %}" type="button" class="btn default">Cancel</a>
        </div>
    </form>
{% endblock %}

web/templates/web/users/evaluate.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% block content %}
    <div class="row">
        <div class="col-md-7">
            <h3 class="col-md-4">Evaluate Student</h3>
        </div>
    </div>

    {% include "message.html" %}

    <form role="form" class="form-horizontal" method="post">
        {% csrf_token %}
        <div class="row">
            <div class="col-md-7">
                {% bootstrap_form form %}
            </div>
        </div>
        {% if evaluation %}
        <div class="row">
            <div class="col-md-7">
                <div class="form-group">
                    <label>Previous Assessor</label>
                    <input class="form-control" disabled value="{{ evaluation.4 }} ({{ evaluation.3 }})"/>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-7">
                <div class="form-group">
                    <label>Previous Evaluation</label>
                    <textarea style="width: 1005px; height: 100px" disabled>{{ evaluation.5 }}</textarea>
                </div>
            </div>
        </div>
        {% endif %}
        {% if perms.web.add_evaluation %}
        <div class="row">
            <div class="col-md-7">
                <div class="form-group">
                    <label>Assessor</label>
                    <input class="form-control" placeholder="Assessor" disabled value="{{ request.user.full_name }} ({{ request.user.employee_id }})"/>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-7">
                <div class="form-group">
                    <label>Evaluation</label>
                    <textarea name="evaluation" class="text" style="width: 1005px; height: 200px"></textarea>
                </div>
            </div>
        </div>
        <div style="margin-left: -15px; margin-top: 20px">
            <button type="submit" class="btn success">Add</button>
            <a href="{% url 'web:course_management' course_id %}" type="button" class="btn default">Cancel</a>
        </div>
        {% else %}
            <a href="{% url 'web:course_management' course_id %}" type="button" class="btn default">Back</a>
        {% endif %}
    </form>
{% endblock %}

web/templates/web/users/list.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% load static %}
{% block content %}
    <div class="row">
        <div class="col-md-7">
            <h3 class="col-md-4">Users</h3>
            <a href="{% url 'web:user_add' %}" type="button" class="btn success pull-right" style="margin-top: 15px">Add</a>
        </div>
    </div>

    {% include "message.html" %}

    <form role="form" class="form-horizontal" method="post">
        {% csrf_token %}
        <div class="row">
            <div class="col-md-7">
                {% bootstrap_form form %}
            </div>
        </div>
        <button class="btn success" type="submit" style="margin-left: -15px">Search</button>
    </form>
    <div class="col-md-7">
    <table class="table table-striped table-bordered table-condensed responsive mb0" style="background: #93a1aa; color: black; margin-top: 20px">
        <thead>
            <tr>
                <th>Employee ID</th>
                <th>Full Name</th>
                <th>Department</th>
                <th>Role</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            {% for s in users %}
            {% if s.13 is not None %}
                <tr>
                    <td>{{ s.11 }}</td>
                    <td>{{ s.12 }}</td>
                    <td>{{ s.14 }}</td>
                    <td>{{ s.13|yesno:'Teacher,Student' }}</td>
                    <td>
                        <a class="btn btn-xs primary" href="{% url 'web:user_management' s.11 %}">Management</a>
                        <button class="btn btn-xs danger" onclick="remove(this)" data-id="{{ s.11 }}"
                        data-url="{% url 'web:user_delete' s.11 %}">Remove</button>
                    </td>
                </tr>
            {% endif %}
            {% endfor %}
        </tbody>
        </table>
    </div>
{% endblock %}

{% block body_js %}
<script src="{% static 'vendor/jquery/dist/jquery.min.js' %}"></script>
<script src="{% static 'vendor/sweetalert/sweetalert.2.0.min.js' %}"></script>
<script>
function remove(e) {
    var id = e.getAttribute('data-id');
    swal({
        icon: "warning",
        title: "You are removing employee " + id +'!',
        buttons: true,
        dangerMode: true,
        closeOnClickOutside: false
    }).then(function(ok) {
        if(ok) {
            var url = e.getAttribute('data-url');
            $.ajax({
                url: url,
                type: "GET",
                success: function (response) {
                    location.reload()
                },
            })
        }
    })
}


</script>
{% endblock %}

web/templates/web/users/management.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% load static %}
{% block content %}
    <div class="row">
        <div class="col-md-7">
            <h3 class="col-md-4">User Management</h3>
        </div>
    </div>

    {% include "message.html" %}

    <form role="form" class="form-horizontal" method="post">
        {% csrf_token %}
        <div class="row">
            <div class="col-md-7">
                {% bootstrap_form form %}
            </div>
        </div>
        <div class="row">
            <label>Courses</label>
        </div>
        <div class="row">
            <div class="col-md-7">
                <table class="table table-striped table-bordered table-condensed responsive mb0" style="background: #93a1aa; color: black;">
                <thead>
                    <tr>
                        <th class="col-xs-1"><input type="checkbox" name="select-all" id="select-all" /></th>
                        <th class="col-md-4">Name</th>
                        <th class="col-md-2">Start Date</th>
                        <th class="col-md-2">End Date</th>
                    </tr>
                </thead>
                <tbody>
                    {% for c in courses %}
                    {% if c in joined_courses %}
                        <tr class="checkboxlist">
                            <td><input type="checkbox" name="courses" value="{{ c.0 }}" checked title=""/></td>
                            <td>{{ c.1 }}</td>
                            <td>{{ c.2|default_if_none:'' }}</td>
                            <td>{{ c.3|default_if_none:'' }}</td>
                        </tr>
                    {% endif %}
                    {% endfor %}

                    {% for c in courses %}
                    {% if c not in joined_courses %}
                        <tr class="checkboxlist">
                            <td><input type="checkbox" name="courses" value="{{ c.0 }}" title=""/></td>
                            <td>{{ c.1 }}</td>
                            <td>{{ c.2|default_if_none:'' }}</td>
                            <td>{{ c.3|default_if_none:'' }}</td>
                        </tr>
                    {% endif %}
                    {% endfor %}

                </tbody>
                </table>
            </div>
        </div>
        <div style="margin-left: -15px; margin-top: 20px" class="row">
            <button type="submit" class="btn success">Save</button>
            <a href="{% url 'web:user_list' %}" type="button" class="btn default">Cancel</a>
        </div>
    </form>
{% endblock %}

{% block body_js %}
<script src="{% static 'vendor/jquery/dist/jquery.min.js' %}"></script>
<script>
    $('#select-all').on('change', function() {
        $('.checkboxlist input[type="checkbox"]').prop('checked', this.checked);
    });

    $('.checkboxlist input[type="checkbox"]').on('change', function () {
        var allChecked = $('.checkboxlist input:checked').length === $('.checkboxlist input').length;
        $('#select-all').prop('checked', allChecked);
    });


</script>
{% endblock %}